### PR TITLE
Add missing imports

### PR DESCRIPTION
**Pull request by renanpvaz**
Hey! I tried using this plugin locally and it failed because these imports were missing, once I added them everything worked

### CODE REVIEW

**Comment by qpwo** [comment]
Adding imports also worked for me

**Comment by rw3iss** [comment]
Thanks... though I prefer 4 space indentation ;p

**Comment by renanpvaz** [comment]
hey @rw3iss I think you didn't mean to merge this, sorry I forgot that I had this PR open and I was doing some testing yesterday. This PR was only supposed to add the missing imports!

**Comment by rw3iss** [comment]
@renanpvaz Thanks... reverted... and added the missing imports. Sorry, should have taken a closer look. 

However, want to note that... I have not been using this plugin anymore.
Instead, I have resorted to using standard 'dotenv' package, and then combining them into the 'define' property of the esbuild script, ie:

```
dotenv.config();
const define = {};
for (const k in process.env) {
    // Bypass windows errors
    if (k === 'CommonProgramFiles(x86)' || k === 'ProgramFiles(x86)') {
        continue;
    }
    define[`process.env.${k}`] = JSON.stringify(process.env[k])
}

// later:
esbuild.build({
    define,
    ...
})
```

Which seems to work fine. I forget why I did this, I think to combine existing environment variables with the .env file... or something.

**Pull request merged**
